replicaCount: 1

image:
  repository: haiderzafar/shine
  tag: v1.0.0
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 3130

env:
  mongodbUri: "mongodb://your-mongo-service:27017/shine"
  sessionSecret: "change-me"
  emailUser: "haiderzafar486@gmail.com"
  emailPass: "Haider@2002"
